#!/usr/bin/env bash
# Change localhost and facebook.com IP
cp /etc/hosts /etc/hosts2
sed -i "s/127.0.0.1/127.0.0.2/" /etc/hosts2
echo "8.8.8.8 facebook.com" >> /etc/hosts2
cp -f /etc/hosts2 /etc/hosts
rm /etc/host2